services:
  _defaults:
    autowire: true
    autoconfigure: true

  command.make.endpoint:
    class: Symfobooster\Devkit\Command\MakeEndpointCommand
    arguments:
      $projectDir: '%kernel.project_dir%'
      $manifestLoader: '@make.endpoint.manifest_loader'
    tags:
      - { name: 'console.command' }

  make.endpoint.manifest_loader:
    class: Symfobooster\Devkit\Maker\Endpoint\ManifestLoader
    arguments:
      $projectDir: '%kernel.project_dir%'
      $validator: '@Symfony\Component\Validator\Validator\ValidatorInterface'
