services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $projectDir: '%kernel.project_dir%'

  Symfobooster\Devkit\Command\MakeEndpointCommand:
    tags:
      - { name: 'console.command' }
